Story/cloud21
SiLeBAT/mibi-parse-cloud pull request #97
Opened 2024-10-30 13:56 UTC by birgitlewicki

2024-11-04 09:25 UTC, dptolle requested changes

2024-11-04 09:25 UTC, dptolle commented on src/modules/orders/infrastructure/repositories/avvcatalogue.repository.ts
> +} from '../../legacy/model/legacy.model';
Please no dependencies to legacy code

2024-11-04 09:25 UTC, dptolle commented on src/modules/shared/infrastructure/cache/avvcatalogue.cache.ts
> +import { AVVCatalog } from '../../../orders/legacy/model/avvcatalog.entity';
Please no dependencies to legacy code

2024-11-08 21:19 UTC, birgitlewicki commented on src/modules/orders/infrastructure/repositories/avvcatalogue.repository.ts
> +} from '../../legacy/model/legacy.model';
done!

2024-11-08 21:21 UTC, birgitlewicki commented on src/modules/shared/infrastructure/cache/avvcatalogue.cache.ts
> +import { AVVCatalog } from '../../../orders/legacy/model/avvcatalog.entity';
done!

2024-11-13 10:09 UTC, merged